version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: komika-db
    env_file:
      - .env.production
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - komika-network

  adonis:
    build: .
    container_name: komika-app
    env_file:
      - .env.production
    depends_on:
      - postgres
    expose:
      - "3333"
    volumes:
      - comics_data:/app/storage/covers
      - episodes_data:/app/storage/episode-comic
      - pages_data:/app/storage/pages-comic
    networks:
      - komika-network

  nginx:
    image: nginx:alpine
    container_name: komika-nginx
    depends_on:
      - adonis
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - comics_data:/app/storage/metadata/coverUrl
      - episodes_data:/app/storage/metadata/episode-comic
      - pages_data:/app/storage/pages-comic
    networks:
      - komika-network

volumes:
  postgres_data:
  comics_data:
  episodes_data:
  pages_data:

networks:
  komika-network:
    driver: bridge
